services:
  # Qdrant Vector Database
  qdrant:
    image: qdrant/qdrant:v1.7.0
    container_name: qdrant_dev
    restart: unless-stopped
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6333/"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Application
  app:
    build:
      context: .
      target: development
    container_name: nestjs_app_dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      QDRANT_HOST: qdrant
      QDRANT_PORT: 6333
      QDRANT_API_KEY: ""
      QDRANT_HTTPS: false
    ports:
      - "3000:3000"  # Web API port
      - "9229:9229"  # Node.js debugging port
    env_file: .env
#    depends_on:
#      qdrant:
#        condition: service_healthy
    networks:
      - app_network
    volumes:
      - ./src:/app/src  # For live reloading
      - ./package.json:/app/package.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./top_movie.json:/app/top_movie.json
    command: npm run start:debug

volumes:
  qdrant_data:
    driver: local

networks:
  app_network:
    driver: bridge