services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: fastify_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: fastify_db
      POSTGRES_USER: nhan
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - fastify_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nhan -d fastify_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Fastify Application
  app:
    build: .
    container_name: fastify_app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://nhan:password@postgres:5432/fastify_db
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fastify_network
    volumes:
      - ./src:/app/src:ro  # For development - remove in production
      - ./tsconfig.json:/app/tsconfig.json:ro  # TypeScript config


volumes:
  postgres_data:
    driver: local

networks:
  fastify_network:
    driver: bridge